### ISSUE TITLE
[Docs] 문서 병합 및 디렉터리 구조 확정

### ISSUE THREAD

**Issue by seokzin** [algo-itzy/cs-itzy#1]
## TODO
- [ ] 디렉터리 구조 정하기
- [ ] 2회차 스터디 방식 가꾸기

### Backlog
- [ ] Docusaurus
- [ ] CI/CD (Github Action)

**Comment by seokzin** [comment]
무기한 연장
